import { PropsWithChildren } from 'react';

import Head from 'next/head';

import styles from './layout.module.scss';

export const Layout = ({ children }: PropsWithChildren<Record<never, never>>) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className={styles.header} />

      <main className={styles.main}>{children}</main>

      <footer className={styles.footer} />
    </div>
  );
};
